version: '3.8'
services:
  myapp:
    image: kchoijfrog.jfrog.io/jfrog/mykchoisite:2022-10-18
    deploy:
      replicas: 5
  mylb:
    container_name: mylb
    image: kchoijfrog.jfrog.io/jfrog/mylb:2022-10-18
    ports:
      - 80:80